/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        app: {
          bg: "rgb(var(--app-bg) / <alpha-value>)",
          "bg-accent": "rgb(var(--app-bg-accent) / <alpha-value>)",
          surface: "rgb(var(--app-surface) / <alpha-value>)",
          panel: "rgb(var(--app-panel) / <alpha-value>)",
          "panel-strong": "rgb(var(--app-panel-strong) / <alpha-value>)",
          border: "rgb(var(--app-border) / <alpha-value>)",
          text: "rgb(var(--app-text) / <alpha-value>)",
          "text-muted": "rgb(var(--app-text-muted) / <alpha-value>)",
          muted: "rgb(var(--app-text-muted) / <alpha-value>)",
          soft: "rgb(var(--app-text-soft) / <alpha-value>)",
          primary: "rgb(var(--app-primary) / <alpha-value>)",
          "primary-strong": "rgb(var(--app-primary-strong) / <alpha-value>)",
          "primary-contrast": "rgb(var(--app-primary-contrast) / <alpha-value>)",
          "primary-muted": "rgb(var(--app-primary-muted) / <alpha-value>)",
          brand: "rgb(var(--app-brand) / <alpha-value>)",
          "brand-strong": "rgb(var(--app-brand-strong) / <alpha-value>)",
          "brand-soft": "rgb(var(--app-brand-soft) / <alpha-value>)",
          "brand-faint": "rgb(var(--app-brand-faint) / <alpha-value>)",
          "brand-contrast": "rgb(var(--app-brand-contrast) / <alpha-value>)",
          danger: "rgb(var(--app-danger) / <alpha-value>)",
          "danger-muted": "rgb(var(--app-danger-muted) / <alpha-value>)",
          chart: {
            track: "rgb(var(--app-chart-track) / <alpha-value>)",
            green: "rgb(var(--app-chart-green) / <alpha-value>)",
            blue: "rgb(var(--app-chart-blue) / <alpha-value>)",
            purple: "rgb(var(--app-chart-purple) / <alpha-value>)",
            orange: "rgb(var(--app-chart-orange) / <alpha-value>)",
            teal: "rgb(var(--app-chart-teal) / <alpha-value>)",
            pink: "rgb(var(--app-chart-pink) / <alpha-value>)",
            yellow: "rgb(var(--app-chart-yellow) / <alpha-value>)",
            indigo: "rgb(var(--app-chart-indigo) / <alpha-value>)",
            red: "rgb(var(--app-chart-red) / <alpha-value>)",
          },
        },
      },
      boxShadow: {
        "showcase-strong": "0 24px 48px rgb(var(--app-shadow) / 0.12)",
        "showcase-soft": "0 12px 24px rgb(var(--app-shadow) / 0.1)",
        "showcase-soft-dark": "0 12px 24px rgb(var(--app-shadow) / 0.2)",
        "showcase-phone": "0 12px 24px rgb(var(--app-shadow) / 0.25)",
      },
      fontFamily: {
        display: ["var(--font-display)"],
        rounded: ["var(--font-rounded)"],
        serif: ["var(--font-serif)"],
        mono: ["var(--font-mono)"],
      },
    },
  },
  plugins: [],
};
