import type { TopCategoriesPageData } from "@/types/analytics";

export const TOP_CATEGORIES_PAGE: TopCategoriesPageData = {
  dateRange: "May 12 - May 18, 2025",
  distribution: {
    items: [
      {
        amountLabel: "$1,785.00",
        colorClassName: "bg-app-primary",
        label: "Housing",
        momLabel: "42%",
        progress: 42,
        trendTone: "positive",
        varianceLabel: "2.1%",
      },
      {
        amountLabel: "$1,062.50",
        colorClassName: "bg-app-primary/45",
        label: "Food & Dining",
        momLabel: "25%",
        progress: 25,
        trendTone: "negative",
        varianceLabel: "8.4%",
      },
      {
        amountLabel: "$637.50",
        colorClassName: "bg-app-surface",
        label: "Transport",
        momLabel: "15%",
        progress: 15,
        trendTone: "positive",
        varianceLabel: "1.5%",
      },
      {
        amountLabel: "$425.00",
        colorClassName: "bg-app-panel",
        label: "Bills & Utilities",
        momLabel: "10%",
        progress: 10,
        trendTone: "neutral",
        varianceLabel: "0.0%",
      },
      {
        amountLabel: "$340.00",
        colorClassName: "bg-app-border",
        label: "Other",
        momLabel: "8%",
        progress: 8,
        trendTone: "neutral",
        varianceLabel: "0.0%",
      },
    ],
    exportLabel: "Export",
    title: "Distribution Map",
  },
  insights: [
    {
      caption: "Highest Variance",
      detail: "Dining out frequency increased by 40% this period.",
      icon: "alert",
      title: "Food & Dining",
      tone: "negative",
      valueLabel: "+$320.00 vs last month",
    },
    {
      caption: "On Track",
      detail: "under budget",
      icon: "check",
      title: "Transport Budget",
      tone: "positive",
      valueLabel: "-$45.00",
    },
  ],
  searchPlaceholder: "Search transactions...",
  subtitle: "Analytics Overview",
  summaryLabel: "Total Spent (May)",
  summaryValue: "$4,250.00",
  title: "Category Breakdown",
};
