import type {
  ExpenseGroup,
  GroupDetail,
  SettlementForm,
  SettlementGuide,
  SettlementItem,
  SocialFinanceBenefit,
  SocialMetric,
  SplitMember,
} from "@/types/social-finance";

export const SOCIAL_FINANCE_PAGE_CONTENT = {
  searchPlaceholder: "Search groups or transactions...",
  subtitle: "Split group expenses, watch balances, and settle payments without losing track.",
  title: "Social Finance",
} as const;

export const SOCIAL_FINANCE_GROUP_PAGES = ["1", "2", "3"] as const;
export const SOCIAL_FINANCE_GROUP_PAGINATION_LABEL = "Showing 1-4 of 13 groups";

export const SOCIAL_FINANCE_SETTLEMENT_BENEFITS: SocialFinanceBenefit[] = [
  {
    detail: "Calculated for maximum efficiency",
    title: "Minimal transfers",
  },
  {
    detail: "Skip redundant bank transactions",
    title: "Save time & hassle",
  },
  {
    detail: "Guaranteed group resolution",
    title: "Everyone settles up",
  },
];

export const SETTLEMENT_FORM: Record<string, SettlementForm> = {
  "trip-to-ella": {
    amount: "LKR 1,240",
    date: "Jul 16, 2026",
    notes: "Split for the island trip accommodation.",
    sourceWallet: "Main Savings (****3842)",
  },
  "college-friends": {
    amount: "LKR 2,100",
    date: "Jul 17, 2026",
    notes: "Reconcile the weekend reunion expenses.",
    sourceWallet: "Daily Wallet (****1204)",
  },
  "team-outing": {
    amount: "LKR 800",
    date: "Jul 16, 2026",
    notes: "Settle your share for the team dinner.",
    sourceWallet: "Main Savings (****3842)",
  },
  "office-project": {
    amount: "LKR 1,275",
    date: "Jul 18, 2026",
    notes: "Monthly project cost settlement.",
    sourceWallet: "Business Wallet (****7701)",
  },
};

export const SETTLEMENT_GUIDES: Record<string, SettlementGuide> = {
  "trip-to-ella": {
    automatedLabel: "Automated",
    breadcrumb: "SOCIAL FINANCE / TRIP TO ELLA SETTLEMENT",
    ctaLabel: "Send Settlement Requests",
    footerNote: "Paid by one person, then split by the rest automatically.",
    hubAmount: "owes LKR 8,500",
    hubLabel: "Kevindu",
    optimizedPaymentLabel: "3 payments",
    optimizedSummary: "Instead of 6 payments",
    originalPaymentLabel: "Save LKR 7,800 in extra payments",
    participants: [
      {
        amount: "LKR 3,000",
        label: "Nimesh",
        note: "Pays into the main bucket",
        tone: "positive",
      },
      {
        amount: "LKR 1,250",
        label: "Supun",
        note: "Pays remaining balance",
        tone: "positive",
      },
    ],
    savingsLabel: "Low fee",
    subtitle: "Trip to Ella",
    title: "Optimized Settlement",
    youAmount: "Get LKR 7,250",
    youLabel: "You",
  },
  "college-friends": {
    automatedLabel: "Automated",
    breadcrumb: "SOCIAL FINANCE / COLLEGE FRIENDS SETTLEMENT",
    ctaLabel: "Send Settlement Requests",
    footerNote: "Use the shortest path first so everyone settles faster.",
    hubAmount: "owes LKR 4,500",
    hubLabel: "Hasini",
    optimizedPaymentLabel: "2 payments",
    optimizedSummary: "Instead of 4 payments",
    originalPaymentLabel: "Save LKR 2,400 in extra payments",
    participants: [
      {
        amount: "LKR 1,200",
        label: "Dylan",
        note: "Pays his share to the hub",
        tone: "positive",
      },
      {
        amount: "LKR 900",
        label: "Anjali",
        note: "Completes the remaining balance",
        tone: "positive",
      },
    ],
    savingsLabel: "Low fee",
    subtitle: "College Friends",
    title: "Optimized Settlement",
    youAmount: "Get LKR 2,100",
    youLabel: "You",
  },
  "team-outing": {
    automatedLabel: "Automated",
    breadcrumb: "SOCIAL FINANCE / TEAM OUTING SETTLEMENT",
    ctaLabel: "Send Settlement Requests",
    footerNote: "The group clears faster when only the net balances move.",
    hubAmount: "owes LKR 800",
    hubLabel: "Kavindu",
    optimizedPaymentLabel: "2 payments",
    optimizedSummary: "Instead of 3 payments",
    originalPaymentLabel: "Save LKR 1,250 in extra payments",
    participants: [
      {
        amount: "LKR 800",
        label: "Maya",
        note: "Pays the shared amount",
        tone: "positive",
      },
      {
        amount: "LKR 800",
        label: "Joel",
        note: "Pays the remaining balance",
        tone: "positive",
      },
    ],
    savingsLabel: "Low fee",
    subtitle: "Team Outing",
    title: "Optimized Settlement",
    youAmount: "You owe LKR 800",
    youLabel: "You",
  },
  "office-project": {
    automatedLabel: "Automated",
    breadcrumb: "SOCIAL FINANCE / OFFICE PROJECT SETTLEMENT",
    ctaLabel: "Send Settlement Requests",
    footerNote: "Netting the balances avoids round trips between the whole group.",
    hubAmount: "owes LKR 6,200",
    hubLabel: "Aruna",
    optimizedPaymentLabel: "2 payments",
    optimizedSummary: "Instead of 4 payments",
    originalPaymentLabel: "Save LKR 3,100 in extra payments",
    participants: [
      {
        amount: "LKR 1,150",
        label: "Ishan",
        note: "Pays the first share",
        tone: "positive",
      },
      {
        amount: "LKR 925",
        label: "Tom",
        note: "Finishes the remaining balance",
        tone: "positive",
      },
    ],
    savingsLabel: "Low fee",
    subtitle: "Office Project",
    title: "Optimized Settlement",
    youAmount: "Get LKR 1,275",
    youLabel: "You",
  },
};

export const SPLIT_MEMBERS: SplitMember[] = [
  { amount: "LKR 30.00", enabled: true, name: "Alex", role: "Paid" },
  { amount: "LKR 30.00", enabled: true, name: "Mia", role: "Owes" },
  { amount: "LKR 30.00", enabled: false, name: "Liam", role: "Owes" },
  { amount: "LKR 30.00", enabled: true, name: "Sarah", role: "Owes" },
];

export const SOCIAL_METRICS: SocialMetric[] = [
  {
    caption: "You are owed",
    change: "+12% from last month",
    icon: "account-cash-outline",
    tone: "positive",
    value: "LKR 24,680",
  },
  {
    caption: "You owe",
    change: "Next payment in 3 days",
    icon: "cash-minus",
    tone: "negative",
    value: "LKR 18,350",
  },
  {
    caption: "Net balance",
    change: "Positive cash flow",
    icon: "scale-balance",
    tone: "brand",
    value: "LKR 6,330",
  },
  {
    caption: "Active groups",
    change: "Two groups updated today",
    icon: "account-group-outline",
    tone: "neutral",
    value: "8",
  },
];

export const EXPENSE_GROUPS: ExpenseGroup[] = [
  {
    balance: "LKR 3,450",
    id: "trip-to-ella",
    members: 6,
    name: "Trip to Ella",
    position: "You are owed",
    progress: 50,
    progressLabel: "50%",
    recurring: "No",
    tone: "positive",
  },
  {
    balance: "LKR 7,250",
    id: "college-friends",
    members: 12,
    name: "College Friends",
    position: "You are owed",
    progress: 70,
    progressLabel: "70%",
    recurring: "Monthly",
    tone: "positive",
  },
  {
    balance: "LKR 1,850",
    id: "team-outing",
    members: 8,
    name: "Team Outing",
    position: "You owe",
    progress: 28,
    progressLabel: "28%",
    recurring: "No",
    tone: "negative",
  },
  {
    balance: "LKR 4,300",
    id: "office-project",
    members: 4,
    name: "Office Project",
    position: "You are owed",
    progress: 61,
    progressLabel: "61%",
    recurring: "Weekly",
    tone: "positive",
  },
];

export const GROUP_DETAILS: Record<string, GroupDetail> = {
  "trip-to-ella": {
    breadcrumb: "SOCIAL FINANCE / TRIP TO ELLA",
    id: "trip-to-ella",
    members: [
      {
        dueAmount: "LKR 0",
        name: "Sarah Mitchell",
        paidAmount: "LKR 12,400",
        role: "Organizer",
        status: "Settled",
        tone: "positive",
      },
      {
        dueAmount: "LKR 2,480",
        name: "Alex Chen",
        paidAmount: "LKR 0",
        role: "Member",
        status: "Pending",
        tone: "negative",
      },
      {
        dueAmount: "LKR 2,480",
        name: "Priya Silva",
        paidAmount: "LKR 0",
        role: "Member",
        status: "Pending",
        tone: "negative",
      },
      {
        dueAmount: "LKR 2,480",
        name: "Marcus Weber",
        paidAmount: "LKR 0",
        role: "Member",
        status: "Pending",
        tone: "negative",
      },
      {
        dueAmount: "LKR 2,480",
        name: "Elena Rodriguez",
        paidAmount: "LKR 0",
        role: "Member",
        status: "Pending",
        tone: "negative",
      },
    ],
    nextPrediction:
      "Based on group spending patterns, your next adventure could be Kandy (Budget: LKR 60k).",
    overview: [
      { label: "Total Spent", value: "LKR 23,220" },
      { label: "Your Share", value: "LKR 4,464" },
      { label: "Status", value: "You are owed LKR 1,240" },
    ],
    progress: 75,
    progressLabel: "3 out of 5 members have fully settled their shares.",
    settleLabel: "Settle Up",
    subtitle: "Trip to Ella",
    title: "Adventure Overview",
    totalText: "Dinner at Nine Arch",
  },
  "college-friends": {
    breadcrumb: "SOCIAL FINANCE / COLLEGE FRIENDS",
    id: "college-friends",
    members: [
      {
        dueAmount: "LKR 0",
        name: "Nimal Perera",
        paidAmount: "LKR 8,500",
        role: "Organizer",
        status: "Settled",
        tone: "positive",
      },
      {
        dueAmount: "LKR 1,200",
        name: "Hasini Fernando",
        paidAmount: "LKR 3,300",
        role: "Member",
        status: "Pending",
        tone: "neutral",
      },
      {
        dueAmount: "LKR 1,200",
        name: "Dylan Brown",
        paidAmount: "LKR 3,300",
        role: "Member",
        status: "Pending",
        tone: "negative",
      },
      {
        dueAmount: "LKR 0",
        name: "Anjali Kumari",
        paidAmount: "LKR 4,500",
        role: "Member",
        status: "Settled",
        tone: "positive",
      },
    ],
    nextPrediction:
      "Your next reunion could center on a beach day in Mirissa with a LKR 45k budget.",
    overview: [
      { label: "Total Spent", value: "LKR 18,950" },
      { label: "Your Share", value: "LKR 4,740" },
      { label: "Status", value: "You are owed LKR 2,100" },
    ],
    progress: 62,
    progressLabel: "2 out of 4 members have fully settled their shares.",
    settleLabel: "Request Split",
    subtitle: "College Friends",
    title: "Group Overview",
    totalText: "Weekend Reunion",
  },
  "team-outing": {
    breadcrumb: "SOCIAL FINANCE / TEAM OUTING",
    id: "team-outing",
    members: [
      {
        dueAmount: "LKR 800",
        name: "Kavindu Jayasuriya",
        paidAmount: "LKR 0",
        role: "Organizer",
        status: "Pending",
        tone: "negative",
      },
      {
        dueAmount: "LKR 0",
        name: "Maya Thomas",
        paidAmount: "LKR 800",
        role: "Member",
        status: "Settled",
        tone: "positive",
      },
      {
        dueAmount: "LKR 0",
        name: "Rashmi Ali",
        paidAmount: "LKR 800",
        role: "Member",
        status: "Settled",
        tone: "positive",
      },
      {
        dueAmount: "LKR 0",
        name: "Joel David",
        paidAmount: "LKR 800",
        role: "Member",
        status: "Settled",
        tone: "positive",
      },
    ],
    nextPrediction:
      "Keep it small for the next meetup: a city dinner night with a LKR 12k cap looks likely.",
    overview: [
      { label: "Total Spent", value: "LKR 11,600" },
      { label: "Your Share", value: "LKR 2,900" },
      { label: "Status", value: "You owe LKR 800" },
    ],
    progress: 45,
    progressLabel: "3 out of 4 members have settled.",
    settleLabel: "Pay Now",
    subtitle: "Team Outing",
    title: "Event Snapshot",
    totalText: "Monthly Outing",
  },
  "office-project": {
    breadcrumb: "SOCIAL FINANCE / OFFICE PROJECT",
    id: "office-project",
    members: [
      {
        dueAmount: "LKR 0",
        name: "Aruna Dias",
        paidAmount: "LKR 6,200",
        role: "Lead",
        status: "Settled",
        tone: "positive",
      },
      {
        dueAmount: "LKR 1,150",
        name: "Ishan Wickram",
        paidAmount: "LKR 2,800",
        role: "Member",
        status: "Pending",
        tone: "neutral",
      },
      {
        dueAmount: "LKR 0",
        name: "Nadia Khan",
        paidAmount: "LKR 3,100",
        role: "Member",
        status: "Settled",
        tone: "positive",
      },
      {
        dueAmount: "LKR 0",
        name: "Tom Silva",
        paidAmount: "LKR 2,900",
        role: "Member",
        status: "Settled",
        tone: "positive",
      },
    ],
    nextPrediction:
      "A smaller budgeting check-in is due next week, with a likely LKR 25k shared spend cap.",
    overview: [
      { label: "Total Spent", value: "LKR 14,100" },
      { label: "Your Share", value: "LKR 3,525" },
      { label: "Status", value: "You are owed LKR 1,275" },
    ],
    progress: 66,
    progressLabel: "3 out of 4 members have fully settled.",
    settleLabel: "Send Reminder",
    subtitle: "Office Project",
    title: "Project Overview",
    totalText: "Office Project",
  },
};

export const SETTLEMENT_ACTIVITY: SettlementItem[] = [
  {
    detail: "From College Friends - 2h ago",
    icon: "bank-transfer-in",
    id: "payment-received-1",
    title: "Payment Received",
    tone: "positive",
    value: "+ LKR 1,200",
  },
  {
    detail: "To Team Outing - 6h ago",
    icon: "bank-transfer-out",
    id: "payment-sent-1",
    title: "Payment Sent",
    tone: "negative",
    value: "- LKR 800",
  },
  {
    detail: "From Trip to Ella - Yesterday",
    icon: "bank-transfer-in",
    id: "payment-received-2",
    title: "Payment Received",
    tone: "positive",
    value: "+ LKR 2,500",
  },
];
